CREATE OR REPLACE TRIGGER tr_upt_emp 
AFTER INSERT OR DELETE OR UPDATE ON emp
FOR EACH ROW
BEGIN
  IF INSERTING THEN
    INSERT INTO AUDIT_EMP VALUES (:new.Empno, :new.ename, :new.job, 'INSERT', USER);
  ELSIF DELETING THEN
    INSERT INTO AUDIT_EMP VALUES (:old.Empno, :old.ename, :old.job, 'DELETE', USER);
  ELSIF UPDATING THEN
    INSERT INTO AUDIT_EMP VALUES (:old.Empno, :old.ename, :old.job, 'UPDATE', USER);
  END IF;
END;
/
